### ISSUE TITLE
Update Users PATCH /application/{id}/collaborators/{collaboratorId}

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-api#10]
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/98829dce-97a4-4d36-8c19-6d2dd5559658)

# Expected Behaviour 
- https://dac.qa.argo.cancercollaboratory.org/api/api-docs/#/Application/patch_applications__id__collaborators__collaboratorId_ 
- Should update the details of a user on an application after using the endpoint 
- - only during DRAFT stages

**Comment by blabadi** [comment]
Changed to PUT instead of PATCH to be correct in terms of HTTP verbs for this endpoint since updates the full resource
