### ISSUE TITLE
🐛 Upload/Delete a ethics file in SIGN AND SUBMIT state

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#107]
## Describe the bug
The user should be able to delete/upload an ethics letter when in "SIGN AND SUBMIT" state. Currently clicking on the trashcan does nothing. And uploading another document does nothing.

Video from Rosi showing steps:

https://drive.google.com/file/d/1M1uN5IRERUxGQomVR53c9IlFlWQ0px09/view

**Comment by kcullion** [comment]
tested in QA and was able to add/edit ethics letter when in sign and submit state. thanks @anncatton

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
