### ISSUE TITLE
🐛 Revisions email shows undefined for ethics

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#108]
## Describe the bug
When I request revisions for all sections, I see an "undefined" for Section E: Ethics

![image](https://user-images.githubusercontent.com/18424138/126536552-1147dbe8-c595-419a-9046-523f8c433451.png)

**Comment by kcullion** [comment]
I now see ethics as ethics, not undefined. Thanks @blabadi 
![image](https://user-images.githubusercontent.com/18424138/126700561-3b0775c6-7ac3-42a3-9847-da16c826353b.png)

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
