### ISSUE TITLE
Request revisions Email: sections are out of order

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#118]
Section C is showing after section D for some reason (not a show stopper)
Note: this was on staging when receiving email in my oicr email address

![image.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/1f5c8b73-7215-49a7-a5e7-e6e1101b616d)

**Comment by kcullion** [comment]
tested in QA Aug 11. The alphabet has been restored! thanks @anncatton 
![image](https://user-images.githubusercontent.com/18424138/129087190-2c7e8527-25e5-4e9a-9c4f-437e2cbd8b6d.png)

**Comment by kcullion** [comment]
Aug 16: working in staging

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
