### ISSUE TITLE
🐛 Staging: emails are NOT sending

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#121]
## Describe the bug
**The problem is: we need updated DACO email passwords to give to Henro to update vault**

Bug found by Ana on staging:
- Applicant is not getting the emails

## Steps To Reproduce

Steps to reproduce the behaviour:
1. submit an application with real email addresses, no emails sent
2. request revisions, no emails sent
3. approve application, no emails sent

## Expected behaviour
Emails should send - we need to update the passwords in vault

**Comment by kcullion** [comment]
Just waiting on Carol to reset no-reply password (email sent July 29)
Rosi will send the daco@icgc-argo.org password to Henro and see if that needs to be updated, as it currently isn't sending the emails in staging.

**Comment by rosibaj** [comment]
confirmed to be working now.
