### ISSUE TITLE
🐛 File Download: Corrupted zip folder

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#123]
## Describe the bug
(See DACO-127 on QA)
Certain pdf files are creating a corrupted zip folder for me - I can't unzip and Sam tried in the terminal and got this message
![image (78)](https://user-images.githubusercontent.com/18424138/127049499-62eb0adb-28e7-45b9-9fdd-cc4fe939dc6b.png)

I tried again on DACO-129, uploading a docx file for the ethics letter. When I submit then download the signed pdf I get 
![image](https://user-images.githubusercontent.com/18424138/127199857-ca31df99-a60c-4521-ba4a-56b6fbb182ab.png)

I can send you the pdfs and docx files that I tried uploading as ethics letters

I also asked Jaser to try unzipping on his Linux machine and he couldn't either
![image (79)](https://user-images.githubusercontent.com/18424138/127211186-dff18d3b-f5d8-4a6b-8b31-602ef2474a18.png)

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Fill out an application
2. Upload the file that Kim sends as your ethics letter
3. Submit application
4. Download the signed pdf from this application
5. try unzipping on a mac and see if it works

## Expected behaviour
The zip folder should not be corrupt

**Comment by rosibaj** [comment]
have dl several times on QA; all successful downloads where i can open the zip. 

@kcullion any reports from you?

**Comment by kcullion** [comment]
@rosibaj @blabadi @anncatton this seems to be working well! As reported on slack, when I download DACO-193 on QA it takes about 7-10 seconds to download. But 
1. this could me my internet - I've been having issues
2. I think this is fine. Especially since we have the loader state on the button.

Well done on this one!

**Comment by rosibaj** [comment]
@kcullion i tried DACO193 and it took about 1.6 seconds

**Comment by kcullion** [comment]
@rosibaj perfect! I'll have to call techsavvy

**Comment by rosibaj** [comment]
Closing as these changes have made it to production.
