### ISSUE TITLE
[BE]: Update PATCH for Upload and Store signed pdf

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#13]
- Ability to submit an application pdf that is signed 
- change a field name from signedAtUtc to uploadedAtUtc because that is more accurate

## Expected outcome for testing
- can upload the pdf and have it attached to application
- the PATCH endpoint completes the transition when the state is submitted

**Comment by rosibaj** [comment]
![image](https://user-images.githubusercontent.com/15824252/123662659-aafad980-d803-11eb-8e63-6f32f32ac499.png)

Can see the correccted field name in requests now! 
thanks @blabadi !
