### ISSUE TITLE
Email to Collaborator: Access is removed (when deleted from approved application)

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#135]
## Goal
When a collaborator is removed from an approved application, the following email needs to be sent to them.

In zeplin: https://zpl.io/anzgoWr
![image](https://user-images.githubusercontent.com/18424138/128910563-a84480c8-7de3-4a34-9a9f-ff8bdcadbb7f.png)

## Expected Outcomes
- [x] The email has the correct content
- [ ] The email has the correct application data coming through
- [ ] The email is to the collaborators email addresses (institutional and google)
- [x] All of the links are same as within the template ("contact the ICGC DACO team" links to https://platform.icgc-argo.org/contact)
- [ ] The email is triggered when an applicant/submitter removes a collaborator from an `APPROVED` application
![image](https://user-images.githubusercontent.com/18424138/128060708-b9eeffa1-6a8a-4940-ae4e-693b19540429.png)

**Comment by kcullion** [comment]
tested on QA aug 11 - by removing collaborators from an approved application. 
The email is sent and it's all looking good. Thanks @anncatton

**Comment by kcullion** [comment]
Aug 16: working in staging

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
