### ISSUE TITLE
[API]Appendices

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#136]
Please revise the list of appendices to only include these 

- [x] APPENDIX I
Title: APPENDIX I - ICGC ARGO Goals and Policies
Link: https://www.icgc-argo.org/page/72/introduction-and-goals- 
ID: stays the same at appendix_icgc_goals_policies
- [x] APPENDIX II 
Title: APPENDIX II - Data Access and Data Use Policies and Guidelines
Link: https://www.icgc-argo.org/page/132/data-access-and-data-use-policies-and-guidelines
ID: Change to: `appendix_data_access_policy`
- [x] APPENDIX III 
Title: APPENDIX III - Intellectual Property Policy
Link: https://www.icgc-argo.org/page/78/e4-intellectual-property
ID: Change to: `appendix_ip_policy`

Related UI ticket is here: https://github.com/icgc-argo/dac-ui/issues/330

**Comment by kcullion** [comment]
changes look good, thanks @anncatton !

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
