### ISSUE TITLE
[BE]: Application PDF Generation - Draft

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#14]
- ability to generate a pdf based on the application content
- pdf is not saved anywhere 
-
**OPTIONS:**
- library to generate html--> pdf 
- headless browser environment and simulate the form?
- can next JS do pdf generation? 
- FE?

## Expected Scope
- decide on our pdf generation after investigation

**Comment by rosibaj** [comment]
From webdev: 

>Add a new PDF report
>All websites use pdfmake (https://github.com/bpampuch/pdfmake) to create PDF files basing on a submission 
For now, we could generate different PDF files based on a submission. To do this, in the `ws-xxx` module, we need to implement the invoke function: `submissionTplAlter`. In this function, it will receive an argument called key which has been defined in the form setup. Based on the key, this function will alter the submissionTpl and return it to ws-core.
 
>For example, we need to add a new PDF report called Foo.  
>First, we login to the website, and go to the form setup. In the “Submission Download Setting” section, we add Foo as key. Label could be any human readable string. Set “enable” to YES, and “Bulk Action” to NO.
Second, we need to create a new PDF template in `ws-xxx` module. We could name it like: submission-foo.js
Last, we need to add function: `submissionTplAlter` in `ws-xxx` module. In the function, we just load submission-foo.js when the key is Foo, and use it as `submissionTpl`.

**Comment by anncatton** [comment]
Chose [react-pdf](https://react-pdf.org/) for pdf generation, as it uses react and appears to be well-supported, with a solid community of contributors. Documentation looks decent. I was able to generate a basic title page w/watermark + page # and footer.
This *will* require creating a PDF-specific layout with these lib components. Also, after discussion with @joneubank @rosibaj and @kcullion, decided we'll need to create some sort of constants/single source of truth setup for the application form text so it is not duplicated between the site ui and the pdf layout.
