### ISSUE TITLE
[ContentUpdates]DACO Emails

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#140]
## All emails (to Applicant/Collaborator and DACO Admin)
Please update the following in the footer of all emails
- [x] `Policies and Guidelines` link to: https://www.icgc-argo.org/page/72/introduction-and-goals- (this one may already be the right link)
- [x] `Help Guides` link to: https://docs.icgc-argo.org/docs/data-access/daco/applying
- [x] `Controlled Data Users` link to https://www.icgc-argo.org/page/139/controlled-data-users

## Email to Applicant: We have received your application 
- [x] wording under the application info box, please change to the content within zeplin: https://zpl.io/VQJY1Wx
- [x] `Help Guides for ICGC DACO Review` link to https://docs.icgc-argo.org/docs/data-access/daco/approval#review-process
![image](https://user-images.githubusercontent.com/18424138/126379590-bfae49b1-24ad-4c49-87b2-9b2fdde52e03.png)

## Email to Applicant: Your Application has been Approved!
- [x] remove link for `Data Access Agreement` 
- [x] see zeplin for new content: https://zpl.io/VQJYDmA 
Really, it's just removing the "s" from 2 years period
- [x] Ana would like to be sent this message for her records, so please B'CC daco@icgc-argo.org on this email

![image](https://user-images.githubusercontent.com/18424138/128365898-852ff5c9-83a6-4b6d-a37b-658709c0fadf.png)

## Email to Collaborator:You have been Granted Access
- [x] remove link for `Data Access Agreement` 
- [x] see zeplin for new content: https://zpl.io/aNO0r8d 
Really, it's just removing the "s" from 2 years period
- [x] `Data Access Policies` link to: https://www.icgc-argo.org/page/132/data-access-and-data-use-policies-and-guidelines
![image](https://user-images.githubusercontent.com/18424138/128366250-407af979-df57-42fe-856e-97b98a16640f.png)

## Email to Applicant: Your Application has been Reopened for Revisions
New zeplin: https://zpl.io/adK7Z5n 
- [x] Change help guide link copy to `Help Guides for Requested Revisions` and link to https://docs.icgc-argo.org/docs/data-access/daco/approval#requested-revisions
- [x] Ana would like to be sent this message for her records, so please B'CC daco@icgc-argo.org on this email
![image](https://user-images.githubusercontent.com/18424138/126382843-ad848c66-18e3-4d80-b007-936a5a04483f.png)

**Comment by kcullion** [comment]
Tested all the emails and looks like you got all these changes, thanks @anncatton 

As discussed, I made this ticket for @rosibaj to help us test the B'cc when we push to staging.

**Comment by kcullion** [comment]
Aug 16: working in staging

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
