### ISSUE TITLE
[UI+Data Hookup] Email to Applicant: Application Rejected

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#142]
## Goal
Using the template built in https://github.com/icgc-argo/dac-ui/issues/66 build and hookup the email that is sent to the applicant when their application is rejected.

Mockup in zeplin: https://zpl.io/V4G8YRM
![image](https://user-images.githubusercontent.com/18424138/128724658-ce538d90-7f55-4624-a183-0d9617af4564.png)

## Expected Outcomes
- [x] The email has the correct content
- [x] 1. The email has the correct application data coming through
- [x] 2. Build the table that displays the details that the DACO ADMIN enters into: https://zpl.io/29GDlql. 
- [ ] 2b. Hide this entire table if the DACO admin doesn't enter any details in this modal.  
- [x] 3. Links
`Help Guides` goes to https://docs.icgc-argo.org/docs/data-access/daco/approval
`Contact the ICGC DACO team` goes to  https://platform.icgc-argo.org/contact

- [x] The email is sent to the **applicant/PI's google email and institutional email addresses** AND **if the submitter is not the applicant/PI - send the email to their gmail address** too. 
- [ ] Ana would like to be sent this message for her records, so please B'CC daco@icgc-argo.org on this email
- [ ] The email is triggered when DACO Admin confirms the rejection - i.e. clicking this `REJECT` button from this modal:
![image](https://user-images.githubusercontent.com/18424138/128756668-8eccca3f-847b-47e1-abda-b174c537cade.png)

**Comment by kcullion** [comment]
@blabadi this looks good. 
Is it possible to hide this whole box if Ana decides not to add any notes in the UI modal?

![image](https://user-images.githubusercontent.com/18424138/133290555-0a9d315a-2941-4dde-afd7-37890923fca3.png)

**Comment by blabadi** [comment]
will do

**Comment by kcullion** [comment]
Tested in QA again and the detail box is gone if I don't submit details. Thanks @blabadi !
![image](https://user-images.githubusercontent.com/18424138/133620730-ac1eacfe-2b07-4189-956b-43fa0cf2b470.png)
