### ISSUE TITLE
[BE] DACO Admin application state post approval (allow editing)

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#146]
API ticket for this one: https://github.com/icgc-argo/dac-ui/issues/357

## Goal

As a DACO administrator, once approved, I need to be able to add/remove collaborators and add ethics letters (if applicable).

## Expected Outcomes

- [x] The APPROVED application for DACO Admin should have the same functionality as the APPROVED application for the applicant
- [x] Unlock collaborators and allow admin to add and remove collaborators
- [x] Unlock ethics section (if the applicant required an ethics letter) and allow DACO admin to upload new letters

![image](https://user-images.githubusercontent.com/18424138/129044257-53fc6fa2-f0ed-4cc2-9339-b784fcb90afd.png)

**Comment by rosibaj** [comment]
Tested Sept 20 4:17 through thte UI 
- all actions work as expected; no bugs 
- thank you @blabadi !!!
