### ISSUE TITLE
Reminder: Test B'CC emails when push to staging

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#149]
@rosibaj with our next push to staging, can you help test that the following emails are being b'cc sent to daco@icgc-argo.org (I don't have the password anymore)

- [ ] Email to Applicant: Your Application has been Approved!
- [x] Email to Applicant: Your Application has been Reopened for Revisions

Mailhog wasn't allowing for us to test this.

This is a followup to this ticket https://github.com/icgc-argo/dac-api/issues/140

**Comment by kcullion** [comment]
@rosibaj @anncatton I see the Approved and Revisions requested emails being sent to the daco email from staging.

**Comment by rosibaj** [comment]
@kcullion @anncatton this too looks like it is working to me.  i see the BCC'd emails in the daco inbox.

**Comment by kcullion** [comment]
Great. @rosibaj should we just close this ticket then?
