### ISSUE TITLE
[BE]: Download ZIP - signed pdf and ethics letter

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#15]
- when an application is SIGNED AND SUBMITTED and includes an ethics letter, then the "Signed PDF" download would be a zip folder of both the signed application and the ethics letter file
- all users have access to this file (applicant + reviewer) 
- this is only available AFTER `SIGN and SUBMIT` state (in `DACO REVIEW`, `APPROVED`)
- this is not available in `DRAFT` and `SIGNED AND SUBMIT` 
-  Zip package should be named `[DACO-1234]-[2021-01-01-4:35]`, and the files inside will be named the same as what the submitter uploaded

**Comment by rosibaj** [comment]
https://dac.qa.argo.cancercollaboratory.org/api/api-docs/#/Application/get_applications__id__assets_APP_PACKAGE

**Comment by rosibaj** [comment]
@blabadi can i request one small change please? 
Can we change the format of the zip package name to this: 
`DACO-1234-20210101.zip` --> [Daco app id]-[date (no time)]

**Comment by rosibaj** [comment]
Tested June 28, 11:47
- downloads on state appear to be working correctly 
- content in zip download is reflected correrctly.

**Comment by rosibaj** [comment]
file name change verified on QA.  thank you @blabadi !
