### ISSUE TITLE
API should not remove duplicate publication and should return an error on any repeated value

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/dac-api#150]
- did a check for duplicates and remove the duplicate
- return that array without duplicate 
- show error in the body when a duplicate has been submitted 

Required for : https://github.com/icgc-argo/dac-ui/issues/138

**Comment by kcullion** [comment]
I think I see this working in postman...the duplicate URL is maintained in the field and I see an incomplete with the error message:
![image](https://user-images.githubusercontent.com/18424138/132389904-81a34115-2e78-4258-a50a-e2e859fb6353.png)
