### ISSUE TITLE
Validate that there is no repeated emails between applicant-> collaborator

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/dac-api#151]
Required for: https://github.com/icgc-argo/dac-ui/issues/329

- Validate that there is no repeated emails between applicant-> collaborator. Applicant takes precedent. 

## For testing

- [ ] Finish testing the UI for this case, once the API is updated the UI should show the errors

**Comment by caravinci** [comment]
As requested in planning, here is the error message displayed under the UI fields: 
`The applicant does not need to be added as a collaborator`

However, I believe the API already has a determined error for this validation, which works well for us.

**Comment by rosibaj** [comment]
@anncatton how in progress is this ticket?

**Comment by anncatton** [comment]
@rosibaj i set up the collaborator errors to return the specific email field with the issue, like: 
`{
        field: 'institutionEmail',
        message: 'The applicant does not need to be added as a collaborator.',
 },
{
        field: 'googleEmail',
        message: 'The applicant does not need to be added as a collaborator.',
}
`
So it can be possible for one collaborator to have up to 2 email errors. Do you want more specific info in the message portion?

**Comment by rosibaj** [comment]
@anncatton i think that this is sufficient! if you think its workign then we just need @kcullion to give it a quick QA later!

**Comment by kcullion** [comment]
@anncatton @rosibaj I can't find where this bug would have been - I see the error messages working as expected.

**Comment by anncatton** [comment]
I tested with new applications...i'm not sure if there are any existing ones in the right state?

**Comment by kcullion** [comment]
I tested with a new application too @anncatton - so this should be good if it works in new applications. Thanks!
