### ISSUE TITLE
Email when Access is removed (when CLOSING an APPROVED Application) 

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#152]
## Goal
As a DACO Administrator, DACO Applicant and Collaborator, I should receive an email confirmation letting me know that my access has been removed. This is when the application was approved and is closed by the applicant or DACO Admin.

## Email that gets sent to the Applicant (and B'CC DACO Admin)
Mockup in zeplin: https://zpl.io/brG33jX
![image](https://user-images.githubusercontent.com/18424138/130516149-63f9fa35-c8e6-4a7d-87cd-5c66dbd8eea3.png)

**Expected outcomes:**
- [x] The email has the correct content
- [x] The email has the correct application data coming through. 
- [x] `Access Expired on` is the date that the application was closed.
- [x] The email is sent to the applicant/PI's google email and institutional email addresses AND if the submitter is not the applicant/PI - send the email to their gmail address too.
- [ ] Ana would like to be sent this message for her records, so please B'CC daco@icgc-argo.org on this email
- [x] All of the links are same as within the template ("contact the ICGC DACO team" links to https://platform.icgc-argo.org/contact)
- [x] One additional link "fill out this short feedback survey" links to this survey: https://docs.google.com/forms/d/1OeRKUPsN4dUaoonR82RLyoPkeMFrtfrm1Ms9_CRGL10/edit?ts=611ae47c
- [ ] The email is triggered when an the applicant/submitter OR DACO Admin closes an application that was in the `APPROVED` state, so when they click the "Yes, Confirm" button from the modal built in: https://github.com/icgc-argo/dac-ui/issues/371 
![image](https://user-images.githubusercontent.com/18424138/129261048-e03cd637-86f7-4f73-895e-e69879a2fc98.png)
## Email that gets sent to the Collaborators on this approved application (do not need to B'CC DACO Admin for this one)

- [x] When the applicant or DACO Admin confirms to close the application in the last step above, the email that was built in this ticket should be sent to all collaborators email addresses (institutional and google)
https://github.com/icgc-argo/dac-api/issues/135

**Comment by kcullion** [comment]
This looks great to me, thanks @blabadi !

**Comment by rosibaj** [comment]
lgtm as well! worked for approved adn non-approved applications as expected!

**Comment by rosibaj** [comment]
Confirmed on September 10 after production release
