### ISSUE TITLE
Add revisons_requested flag 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-api#160]
- add flag IF revisions were requested to the revisions requested body in the application 
- follows current reset logic when revision are resubmitted. 
- later this will lead into a UI tag (https://github.com/icgc-argo/dac-ui/issues/299) 

The flag will look like this and it will be removed from the UI when the application isn't in Revisions Requested mode. The progress bar as "Draft, Sign & Submit, DACO Review" will stay the same
![image](https://user-images.githubusercontent.com/18424138/131370257-fa1bc314-87ba-44a8-96fc-7ede4c55aeda.png)

**Comment by blabadi** [comment]
added the flag to the application root object:

```
{
appId: DACO-1,
revisionsRequested: true,
...
}
```
will add it to swagger in another PR as I forgot to do it in the same PR

**Comment by kcullion** [comment]
when testing with postman and I request revisions, I see this flag in the response. Seems to be working. Thanks @blabadi 
![image](https://user-images.githubusercontent.com/18424138/132404102-5bd173b6-9b85-4d73-a206-eb94c7371590.png)

**Comment by kcullion** [comment]
when testing with postman and requesting revisions, I see this flag in the response. Thanks @blabadi 
![image](https://user-images.githubusercontent.com/18424138/132404220-9676ded6-26e1-48d4-810e-857343a88879.png)

**Comment by rosibaj** [comment]
- verified with @kcullion that the flag is cleared once it enters review
![image](https://user-images.githubusercontent.com/15824252/132408832-9386be57-e3be-47ad-8d68-8d1d77ecc67d.png)

lgtm thank  you @blabadi !
