### ISSUE TITLE
[API ]DACO Admin Table: allow for application status counts

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#171]
For UI ticket: https://github.com/icgc-argo/dac-ui/issues/413

- [ ] Count ALL states of applications that exist in the system (will be displaying 4 of these counts on the admin table as in the screenshot)
- [ ] Count will be 0 if none exist for that status (say, for expired)
- [ ] Should also respond to all search terms 

![image](https://user-images.githubusercontent.com/18424138/131893753-0c16a7a9-b4a0-40ec-8a20-7e9e79309b06.png)

**Comment by blabadi** [comment]
search api has two changes to support this: 
1- new parameter to tell the API to return the counts:  `includeStats`
```
{{dac-host}}/applications/?states=&page=0&pageSize=25&sort=state:asc&includeStats=true&query=xyz
```
2- new part in the response that holds this count and any other aggregations in the future:
```
{
  "stats": {
    "countByState": {
      "REVISIONS REQUESTED": 0,
      "APPROVED": 0,
       ....
    }
  },
  "pagingInfo": {
    "totalCount": 0,
    "pagesCount": 0,
    "index": 0
  },
  "items": [
  ....
  ]
}
```

**Comment by kcullion** [comment]
Rosi and I checked in postman and this looks good @blabadi !
