### ISSUE TITLE
[BE]: DACO Admin Table: List and Search

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#2]
**Goal:** Build the endpoint to support list/search on this manage applications table (will be for the DACO administrator to view and filter the table based on the criteria they are looking for). 

Complete this endpoint, including:
![image](https://user-images.githubusercontent.com/18424138/117188715-5ca0ff80-adab-11eb-94ed-a99c47a74837.png)
- [ ] paging
- [ ] search based on parameters 
- [ ] state 
- [ ] auth 

## Expected Behaviour
FOR ENDPOINT 
- [ ] Depending on my admin or user role, ther correct data set shoudl be returned. i.e Admin = all data, user = only my data. 
- [ ] Paging should be available and work to scroll though pages

FOR SEARCH/STATE
- [ ] State filter should return only the expected state results; should accept more than one state.
- [ ] The search should be case insensitive 
- [ ] Should work for numbers too (e.g. to filter just `2021` applications)
- [ ] Should work for partial search. For example, the administrator types `ew` and that should return applications with "Revi`ew`" and "Ren`ew`ing" status

![image](https://user-images.githubusercontent.com/18424138/118281558-58f03580-b49b-11eb-8478-29ff4c50f802.png)

**Comment by blabadi** [comment]
this is ready for testing 

https://dac.qa.argo.cancercollaboratory.org/api/api-docs/#/Application/get_applications_

steps:
- create an application:
POST /applications/

- search for it using query

- fields can be updated using back door endpoint to fill fields like applicant :
PUT ​/applications​/{id} 

(copy the document from the GET /applications/{id} endpoint and modify it, this put endpoint doesn't validate or anything you have to make sure to provide everything correctly)
