### ISSUE TITLE
[API] Collaborator Dashboard Card

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#210]
This card will show on the dashboard will show up ONLY IF the logged in user is a collaborator on an approved application that they don't own. i.e. they have data access from an application that they don't own.

- [ ] Extend the API to send the correct data to this card
- [ ] the card will only show up if there is data

![image](https://user-images.githubusercontent.com/18424138/134538502-381d78d4-11a3-46a3-9fb4-5eddc07c18da.png)

**Comment by anncatton** [comment]
Search will be done with the egoJwt `email` -> collaborator `googleEmail`.

**Comment by kcullion** [comment]
This is working on QA. Thanks @anncatton

**Comment by kcullion** [comment]
added myself as a collaborator on an approved applciation and it showed up correctly on this card in staging
![image](https://user-images.githubusercontent.com/18424138/149841746-7471ecfc-6b1d-4cef-b1c5-03201472b3f0.png)
