### ISSUE TITLE
Email to Applicant: Access has been Paused

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#229]
## Goal
Build and hookup the email that is sent to the applicant when their access has been paused if they haven't completed their annual attestation. 

Mockup in zeplin: https://zpl.io/bloQ7dD
![image](https://user-images.githubusercontent.com/18424138/135489871-638034a2-f87b-4ddd-9de3-a982494ca117.png)

## Expected Outcomes
- [x] The email has the correct content
- [x] 1. The email has the correct application data coming through. New field: **Access Paused on:** this is 1 year after approval date.
![image](https://user-images.githubusercontent.com/18424138/135490032-20b339a2-19ad-42f9-8f8e-fb01f9c6a3fd.png)

- [x] 2. The `Complete Attestation` button takes them to their approved application (log in first if needed).
- [x] 3. Links
`Help Guides for Annual Attestation` goes to https://docs.icgc-argo.org/docs/data-access/daco/renew-close#annual-attestation
- [x] The email is sent to the applicant/PI's google email and institutional email addresses AND if the submitter is not the applicant/PI - send this email to their gmail address too. 
- [ ] **IF THE APPLICANT HASN'T COMPLETED THE ATTESTATION YET** The email is triggered 1 year after the approval date
The email will be sent using this cron job: https://github.com/icgc-argo/dac-api/issues/239

**Comment by b-f-chan** [comment]
Released to prod, prod testing not possible for OICR team, hence we will close this ticket, and open new issues if any are found by users in production.
