### ISSUE TITLE
Email to Applicant (bcc admin): Attestation has been received

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#230]
## Goal
Build and hookup the email that is sent to the applicant when they have completed the attestation. B'CC DACO admin on this. 

Mockup in zeplin: https://zpl.io/2G5XBlE
![image](https://user-images.githubusercontent.com/18424138/135491059-ec83edf3-db92-4f1e-99dc-e68b762e70b1.png)

## Expected Outcomes
- [ ] The email has the correct content
- [ ] 1. The email has the correct application data coming through. New field: **Attested on:** this is the date that the applicant clicks the "I attest to the above terms" button on the application banner
![image](https://user-images.githubusercontent.com/18424138/135491305-04ddff25-68a3-4306-b600-327461647e8d.png)
- [ ] 2. Link
`Help Guides` just goes to https://docs.icgc-argo.org/docs/data-access/daco/applying
- [ ] The email is sent to the applicant/PI's google email and institutional email addresses AND if the submitter is not the applicant/PI - send this email to their gmail address too. Ana would like to be sent this message for her records, so please B'CC daco@icgc-argo.org on this email 
- [ ] The email is triggered when DACO Admin attests on the UI banner, ie. clicks this button:
![image](https://user-images.githubusercontent.com/18424138/135491599-2dd531b9-861b-4b6e-b507-3533cbce1782.png)

**Comment by anncatton** [comment]
Note: BCC can't be verified in dev/qa because mailhog doesn't display this, will need to verify in staging
