### ISSUE TITLE
2 Emails to Applicant: Reminder emails that access is expiring

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#231]
## Goal
Build and hookup the 2 emails that are sent to the applicant
1. 90 days prior to when their access is to expire. Cron job: https://github.com/icgc-argo/dac-api/issues/250
2. 45 days prior to when their access is to expire: Cron job: https://github.com/icgc-argo/dac-api/issues/251

Mockup in zeplin: https://zpl.io/V4ngZmQ
![image](https://user-images.githubusercontent.com/18424138/135665001-fe06717d-5ebb-4a55-8efc-9a6883974077.png)

## Expected Outcomes
- [ ] Build 2 emails, one for 45 days to expiry, one for 90 days to expiry. Content is all the same except for 1 and 2:
- [ ] 1. The title and first paragraph should have the correct # of days to expiry
- [ ] 2. For the 90 day email this should say "you have 180 days to renew" and for the 45 day email this should say "you have 135 days to renew"
- [ ] 3. The `Renew your Access` button takes them to their approved application (log in first if needed).
- [ ] 4.`Help Guides for Access Renewal` goes to https://docs.icgc-argo.org/docs/data-access/daco/renew-close#renewing-an-application
- [ ] The application details box is the same as the one that's on the approved email
- [ ] The email is sent to the applicant/PI's google email and institutional email addresses AND if the submitter is not the applicant/PI - send this email to their gmail address too. 
- [ ] The emails are triggered 90 days and then 45 days prior to the application **expiry date** using the cron jobs: https://github.com/icgc-argo/dac-api/issues/250
https://github.com/icgc-argo/dac-api/issues/251

**Comment by anncatton** [comment]
@kcullion Will not be able to test until email trigger is implemented in #250 and #251
