### ISSUE TITLE
[API] Attestation: New attestationDate field on APPROVED state

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#236]
When application is moved to APPROVED state,  a new calculated field `attestationByUtc` will be returned in the application and app summary responses.
- It will be calculated from the `approvedAtUtc`
- the time period is 1 year for DACO, but will make it configurable for testing purposes

**Comment by anncatton** [comment]
Field will be calculated from `approvedAtUtc`

**Comment by b-f-chan** [comment]
Released to prod, prod testing not possible for OICR team, hence we will close this ticket, and open new issues if any are found by users in production.
