### ISSUE TITLE
[BE] Attestation: Cron job1 to send out reminder email

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#237]
Cron job 1 should:
- [ ] check every day to see which applications have attestation dates that are 45 days from now
- [ ] If so, send out the attestation reminder email : https://github.com/icgc-argo/dac-api/issues/228 
- [ ] field `attestedAtUtc` will be `undefined` for new applications and `null` for renewal applications (this field will be reset when a renewal is approved)

**Comment by b-f-chan** [comment]
Released to prod, prod testing not possible for OICR team, hence we will close this ticket, and open new issues if any are found by users in production.
