### ISSUE TITLE
[BE] Attestation: Cron job2 to send out email that access is PAUSED

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#239]
Cron job 2 should:
- [ ] Bulk check if the `attestationByUtc` is today, and `attestedAtUtc` is `null` or `undefined`. As `attestationByUtc` is a calculated field, the db query will be checking if `approvedAtUtc` is 1 year previous (this duration will be configurable for testing purposes)*
- [ ] If yes, send the email for "Access has been Paused": https://github.com/icgc-argo/dac-api/issues/229
- [ ] Using this endpoint, transition the application to PAUSED state:https://github.com/icgc-argo/dac-api/issues/238 *
* Most of this work was done in #238

**Comment by b-f-chan** [comment]
Released to prod, prod testing not possible for OICR team, hence we will close this ticket, and open new issues if any are found by users in production.
