### ISSUE TITLE
[API] Add search values for Type - for admin Management table

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#242]
Add search value for Type: renewal/new to use in the management table.

- [ ] Requires a migration
- [ ] If isRenewal = false, this is New
- [ ] If isRenewal = true, this is Renewal

UI reference:
![image](https://user-images.githubusercontent.com/18424138/137376798-b2faa580-267d-49ce-9723-3e69993a19dd.png)

**Comment by anncatton** [comment]
Completed as part of #226 
PR: https://github.com/icgc-argo/dac-api/pull/263
