### ISSUE TITLE
[API] PATCH update for when applicant renews an application

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#253]
When the applicant clicks the renew button a few things will need to happen, **including making the applicant re-agree to all of the agreements in the last two sections**. We will need to update the PATCH endpoint to:

- [ ] set isRenewal = true
- [ ] Transition the application into DRAFT state
- [ ] Unlock all sections for edits
- [ ] Clear all checkbox agreements in Section F: Data Access Agreements
- [ ] Clear all checkbox agreements in Section G: Appendices 
- [ ] Clear the sign and submit section

**Comment by anncatton** [comment]
Renewal flow approach has changed, the implementation for the user request will be done in #364
