### ISSUE TITLE
[BE] Approved users for Daco2Ego: to allow project teams access if the renewal application is in non-APPROVED state

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#254]
Modify query used in `/export/approved-users/` endpoint to allow users in renewing applications to maintain access:

- [ ]  In `DRAFT`, `SIGN AND SUBMIT`, `REVISIONS REQUESTED` or  `REVIEW` state + not expired yet. This means the project team still has data access. 

Right now, access is just allowed for applications in `APPROVED` state.

**Comment by anncatton** [comment]
Renewals will be created as separate applications, so the original application will not change state when a user initiates a renewal, and access provided by the original app will remain unchanged.
When a renewal is APPROVED, it will provide access as usual.
