### ISSUE TITLE
[API] Update PATCH endpoint for renewal applications that are approved

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#256]
We need to update the PATCH endpoint so that once a renewal is approved:

- [ ] Check if isRenewal=true when the application is approved
- [ ] Clear out the  fields: isAttested, and reset the attestation date for 1yr in the future
- [ ] If there is an approvedPdf marker isCurrent=true and its approvedAtUtc does not match the new app-level approval date, we set this one to isCurrent=false 
- [ ] `ableToRenew`  will calculate to false
- [ ] reset approval-related fields: `approvedAtUtc`, `expiresAtUtc`

**Comment by anncatton** [comment]
Renewals will be newly created applications so the existing approval email can be used.
