### ISSUE TITLE
Bug: can't submit a pdf when request revisions just reopens the last form section

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#281]
When DACO admin requests revisions and just reopens the "Sign and Submit" section, the applicant cannot actually submit a new pdf:
https://watch.screencastify.com/v/NMcp4O5czzOQxmtAfcGd

API error message: "\"Cannot upload signed application in this state\""

**Comment by anncatton** [comment]
Add special case to allow signed app upload when only signature section in REVISIONS REQUESTED
- add scenario to test suite

**Comment by kcullion** [comment]
Tested in QA and the application is now in the correct state and I am able to submit a new pdf. Thanks @anncatton !
![image.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/4dde41d2-cec4-4204-9e50-87368c0f173a)

**Comment by kcullion** [comment]
Tested in staging, looks good!
