### ISSUE TITLE
Authenticated service for daco cron jobs

### ISSUE THREAD

**Issue by anncatton** [icgc-argo/dac-api#293]
Create a simple authenticated service to call the renewal flow job endpoint in dac-api.
Create a system level permission in Ego for this service.

**Comment by anncatton** [comment]
All batch jobs will be run through one endpoint. We'll set up as a cronjob that uses [http-request-sender](https://github.com/icgc-argo/http-request-sender) script to access this endpoint. This script has been updated to make authenticated requests and retrieve secrets from Vault.

**Comment by anncatton** [comment]
A cronjob has been set up in dev and qa.
Remains to be set up in staging and prod.

**Comment by b-f-chan** [comment]
Released to prod, prod testing not possible for OICR team, hence we will close this ticket, and open new issues if any are found by users in production.
