### ISSUE TITLE
Test daco2ego in Staging and Prod

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#296]
Test use cases:
@anncatton please fill in

Related ticket: https://github.com/icgc-argo/daco2ego/issues/4

**Comment by anncatton** [comment]
@blabadi and @anncatton tested in prod, scenarios outlined [here](https://wiki.oicr.on.ca/display/icgcargotech/Integrations+-+Daco2Ego#IntegrationsDaco2Ego-Mergev1/v2ApprovedLists:AccessRules.1)
