### ISSUE TITLE
DACO Website v1 Support Tasks

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/dac-api#297]
- [x] Ma’n and I to be removed from the daco@icgc.org email list.
  - IT ticket:  https://servicedesk.oicr.on.ca/servicedesk/customer/portal/2/IT-40282

- [x] Amanda and Judith have been added as administrators. They are not, however, able to download PDFs from the DACO portal. This is essential to be able to manage the applications from their side
  - IT Ticket: https://servicedesk.oicr.on.ca/servicedesk/customer/portal/2/IT-40513?sda_source=notification-email 

- [ ] Ma’n’s name will need to be removed from the PDF version of the form as the Data Access Officer, and Judith should be listed instead. I’ve made these changes to the online form and emails already, but I do not have access to the PDF editor.

- [ ] Users should be getting an automatic email when they email the DACO: “Thank you for contacting the Data Access Compliance Office (DACO). Our office will now be managed from the University of Glasgow. During this transition, delays might occur in the application process and email response times. We thank you for your patience and understanding.”

**Comment by akachru-github** [comment]
v2 PDF does not have an explicit "Data Access Officer", so no explicit name is there.

**Comment by kcullion** [comment]
closing this. v1 is now expired - so no further action required from us
