### ISSUE TITLE
Move ega email job to batch-transitions endpoint

### ISSUE THREAD

**Issue by anncatton** [icgc-argo/dac-api#338]
Append EGA email trigger to end of the batch jobs list
As part of this work, add more logging to the job itself and the helper functions (CSV builder, etc).
Separate admin endpoints `/jobs/export-and-email/` and `/export/approved-users/` can be kept.

**Comment by b-f-chan** [comment]
Released to prod, prod testing not possible for OICR team, hence we will close this ticket, and open new issues if any are found by users in production.
