### ISSUE TITLE
[UI and Data Hookup] Admin Dashboard feedback

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#34]
For the admin dashboard: 

DATA:
- [x] 1. Filter out the DRAFT and SIGN AND SUBMIT states - DACO admin wouldn't need to see the applications in that state. 
- [x] 2. `Last Updated Date` is not showing in the table. It should be for ALL applications ALL the time. 
- [x] 3. before the table loads I see a flash of the "No data" state - can you implement the dna loader here instead?
![image](https://user-images.githubusercontent.com/15824252/122245189-81e95900-ce93-11eb-9989-f730b776f333.png)

UI:

- [x] 4. Cant sort on the ethics letter column; should be able to. 
- [x] 5. Add same padding/margin below the table as there is above the table
- [x] Fix the table pagenation bug (can't page through the table)
- [x] 6. Show the blue bar by default on the sorted column (status)
![image](https://user-images.githubusercontent.com/18424138/122266920-51f88080-cea8-11eb-9dbd-37e7a9d905a7.png)

**Comment by samrichca** [comment]
pagination not working - i only see one page available

**Comment by samrichca** [comment]
"before the table loads I see a flash of the "No data" state - can you implement the dna loader here instead?"

@caravinci is gonna address API calls happening before the EGO JWT is checked/loaded so i'll revisit the no data state a bit later. we also need to address loaders while logging in but that's accounted for.

**Comment by kcullion** [comment]
@samrichca I forgot to mention above...the "Sign And Submit" state should be filtered out of this table too. Basically DACO admin should see all applications only in the states possible after submission. 
![image](https://user-images.githubusercontent.com/18424138/122588554-3cf92a00-d02d-11eb-8726-93a34bc398da.png)

**Comment by samrichca** [comment]
- [ ] - DRAFT
- [ ] - SIGN AND SUBMIT
- [ ] - REVIEW
- [ ] - REVISIONS REQUESTED
- [ ] - APPROVED
- [ ] - RENEWING
- [ ] - REJECTED
- [ ] - CLOSED
- [ ] - EXPIRED

**Comment by kcullion** [comment]
@samrichca yep, just filter out DRAFT and SIGN AND SUBMIT

**Comment by samrichca** [comment]
sorting works on:
- status
- access expiry
- last updated
- application #

waiting for backend support for sorting on:
- ethics
- google email
- applicant name
- institution

**Comment by rosibaj** [comment]
BE followup for sorting: https://github.com/icgc-argo/dac-api/issues/49 
UI followup for after No. 49: https://github.com/icgc-argo/dac-ui/issues/147

**Comment by rosibaj** [comment]
@samrichca minus the sorting issue mentioned above, this looks great! 
- was able to add multiple applications and see them in the table 
- once > 5 applications, pagination appears to be working great
- everything loaded  smoothly through multiple logins 
- data is now populating as expected in the table based on the application values

@kcullion any feedback from you?

**Comment by samrichca** [comment]
DEPENDENCIES

UI version 0.8.0

this ticket was made on the wrong repo

**Comment by kcullion** [comment]
I saw 7 submissions but there's only 5 in the table. But then I realized because it defaults to 5 submissions. Can you default to list 20?
![image](https://user-images.githubusercontent.com/18424138/123314422-93b4a700-d4f8-11eb-8ec5-918bcf393650.png)

If the sorting will be taken care of elsewhere, this looks good to me!
