### ISSUE TITLE
Feature Request: Collaborators should be unique in a single application 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-api#35]
Currently, I can submit the same collaborator many times to the same application - this should not be allowed. 

Unique collaborators means: 
- A collaborator is identified by EITHER their institutional email and their google email address 
- Each email can be used only ONCE, and precedence is given the the collaborator that was added first (i.e  assume if an email address was used with an already added collaborator it belongs to them, not the second collaborator being added that duplicates the email address. 
- The `Applicant` cannot be added as a collaborator. 

## Expected behaviour

- [ ] 1. If a second collaborator is added that violates the email validation rules , an error is returned `Collaborator could not be added`  `This collaborator has already been added to your application.
`![image](https://user-images.githubusercontent.com/18424138/122595662-cb25de00-d036-11eb-84b3-77cfef2cc5d2.png)

- [ ] 2. If the applicant tries to add themselves as a collaborator (using EITHER their institutional email or google email or both together) , an error is returned `Collaborator could not be added` `The applicant does not need to be added as a collaborator.`
![image](https://user-images.githubusercontent.com/18424138/122595827-ff010380-d036-11eb-8e50-4e44a77a93e2.png)

**Comment by blabadi** [comment]
I updated swagger to include these error responses, two error codes introduced: COLLABORATOR_EXISTS, COLLABORATOR_SAME_AS_APPLICANT  to communicate this error to FE

**Comment by kcullion** [comment]
I saw these errors happening in postman. Will test again using the UI when it's hooked up

**Comment by rosibaj** [comment]
Errors verified for this in QA!
