### ISSUE TITLE
Refactor getRole calls

### ISSUE THREAD

**Issue by anncatton** [icgc-argo/dac-api#353]
There are now 2 separate functions used to get the role of the user making a request:
- `getUpdateAuthor` is older and only accounts for admins and regular users
- `getDacoRole` was added to account for system permissions used in batch jobs. Right now this is only used in the pause app job and is not in prod, but this implementation should replace the way `role` is defined in  `getUpdateAuthor`.

**Comment by b-f-chan** [comment]
Released to prod, prod testing not possible for OICR team, hence we will close this ticket, and open new issues if any are found by users in production.
