### ISSUE TITLE
Add check for removed sourceAppId in close renewal flow

### ISSUE THREAD

**Issue by anncatton** [icgc-argo/dac-api#395]
In the close renewal transaction, check that the `sourceAppId` has been removed in the renewal app document before proceeding with the changes for the source application document.
Throw an error if the `sourceAppId` is not null, to prevent orphaning the closed renewal.

**Comment by b-f-chan** [comment]
Still in development

**Comment by anncatton** [comment]
Cannot verify in production; will open new ticket should an issue arise.
