### ISSUE TITLE
Make # of Days in all Notification Emails Dynamic

### ISSUE THREAD

**Issue by b-f-chan** [icgc-argo/dac-api#409]
Currently, various emails (such as attestation) show static values for most fields.  For example, the # of days to expiry if a user does not attest.

For example, if there is an outage, and attestation emails are not sent, when the system is back online, the emails are sent immediately but various fields may not reflect the delay.

For example, the Days to Expiry is static (e.g. 45 days to expiry), but if there is an outage for 2 days, when the email is sent again, it won't say 43 days.

We should make all email content and fields as dynamic as possible.

![Screen Shot 2023-03-20 at 3.17.07 PM.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/8ec17ae8-6fef-48d9-bbae-190fdf31ee2e)

**Comment by b-f-chan** [comment]
Prefer doing dac-api#380 first before doing this

**Comment by anncatton** [comment]
Removed number of days from attestation and expiry emails, instead using projected date. Implemented in https://github.com/icgc-argo/dac-api/issues/428
