### ISSUE TITLE
Multiple ethics docs will not be deleted from storage

### ISSUE THREAD

**Issue by anncatton** [icgc-argo/dac-api#414]
To reproduce:
- On a draft application, set ethics doc as required
- upload more than one ethics document
- change ethics doc selection to not required
- the approved documents will be removed from the `sections.ethicsLetter.approvalLetterDocs` array, but the logs will show that only the first document is deleted from storage

**Comment by b-f-chan** [comment]
Tested in real-time with @anncatton, this works fine in QA, moving to Ready for Staging
