### ISSUE TITLE
Fix Content for Expiry Warning Emails

### ISSUE THREAD

**Issue by b-f-chan** [icgc-argo/dac-api#428]
In the expiry warning emails, we should make the following edits to make the content more clear:

- [ ] Rename title to simply say `Your Access is Expiring Soon`.

- [ ] Merge the paragraph before the summary table and after the summary table into a single paragraph at the start, which indicates both the expiry date and the renewal period end date ("renew by" date).  Word as follows: 

`The following application is expiring on [date].  On the date of expiry, all project members will lose access to ICGC Controlled Data.  You have until [date] to renew your project team’s access privileges for another two years.`

- [ ] Revise the final paragraph to be more clear about the renewal process.  Word as follows: 

`You can initiate the renewal process from your DACO application.  You will be required to review and agree to all Data Access policies again before signing and resubmitting.`

![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/cf21ba63-1624-4b5e-8a5b-232fb632ffeb)

**Comment by anncatton** [comment]
The "days to..." language used in the attestation required email will also be updated to use the `attestationBy` date, for clarity.

**Comment by anncatton** [comment]
Cannot verify in production; will open new ticket should an issue arise.
