### ISSUE TITLE
[UI+Data Hookup]: Email to Applicant: Requested Revisions - with dynamic table of revisions

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#44]
## Goal
Using the template built in https://github.com/icgc-argo/dac-ui/issues/66 build and hookup the email that is sent to the applicant when DACO Admin requests revisions.

Mockup in zeplin: https://zpl.io/adK7Z5n
![image](https://user-images.githubusercontent.com/18424138/120838523-e58b9200-c535-11eb-996e-8c9d793a3591.png)

## Expected Outcomes
- [ ] The email has the correct content
- [ ] 1. Build the table that displays the revisions that DACO Admin enters in: https://zpl.io/VOLWoek. This table should only show the sections and details for the items that are checked off by DACO admin. Hide the general comments row if there are no general comments on the application
- [ ] 2. The `Revise Your Application` button takes them to their approved application (log in first if needed), landing on the first section that is reopened for revisions.
- [ ] 3. Links
`Help Guides for Applying for Access` goes to https://docs.icgc-argo.org/docs/data-access/data-access
`Contact the ICGC DACO team` goes to  https://platform.icgc-argo.org/contact
- [ ] The email has the correct application data coming through
- [ ] The email is sent to the applicant/PI's google email and institutional email addresses AND if the submitter is not the applicant/PI - send this email to their gmail address too. 
- [ ] The email is triggered when DACO Admin confirms the request for revisions - i.e. clicking the `Send Request` button from this modal:
![image](https://user-images.githubusercontent.com/18424138/120839104-8a0dd400-c536-11eb-91ff-33fe0d733d0b.png)

**Comment by rosibaj** [comment]
Tested Jul 14, 2021: 
![image](https://user-images.githubusercontent.com/15824252/125662247-0f35b452-0d9e-4da8-935e-245d634f0db3.png)
![image](https://user-images.githubusercontent.com/15824252/125662705-e537e150-0880-45d4-b844-fccd7524e574.png)

Looks excellent @blabadi thank you so much!
