### ISSUE TITLE
[UI+Data Hookup]: Email to Collaborator: You have been Granted Access

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#45]
## Goal
Using the template built in https://github.com/icgc-argo/dac-ui/issues/66 build and hookup the email that is sent to the collaborator when their application is approved or when they are added to an approved application

Mockup in zeplin: https://zpl.io/aNO0r8d
![image](https://user-images.githubusercontent.com/18424138/120836973-2edae200-c534-11eb-883e-144c392d2485.png)

## Expected Outcomes
- [x] The email has the correct content
- [ ] 1. Link Data Access Agreement TBD (likely to a policy page on icgc-argo.org)
- [ ] 2. Link Data Access Policies TBD (likely to a policy page on icgc-argo.org)
- [x] 3. Links
`ICGC ARGO Data Platform` goes to  https://platform.icgc-argo.org/
`ICGC 25K Data Portal` goes to https://dcc.icgc.org/
`icgc-argo.org` goes to https://www.icgc-argo.org/
- [x] 4. Links
`Help Guides for Accessing Controlled Data` goes to https://docs.icgc-argo.org/docs/data-access/data-download
`Contact the ICGC DACO team` goes to  https://platform.icgc-argo.org/contact
- [x] The email has the correct application data coming through
- [x] The email is sent to the **collaborator's** google email and institutional email addresses
- [ ] **TRIGGER 1**: The email is triggered when DACO Admin confirms the approval - i.e. clicking this `approve for access` button from this modal:
![image](https://user-images.githubusercontent.com/18424138/120835680-a1e35900-c532-11eb-84f6-0307c290ca96.png)

- [x] **TRIGGER 2**: This email is also sent when a collaborator is added to an approved application. So when an applicant presses the Add Collaborator button from this modal, and it's successful at adding the collaborator. If this modal fails for some reason, then an error banner will show in the modal and the email shouldn't send.
![image](https://user-images.githubusercontent.com/18424138/120837799-29ca6280-c535-11eb-9a29-2df3be24cf07.png)

**Comment by rosibaj** [comment]
Tested Jul 21, 2021 12:21
- added a collaborator to an approved application and received all the expected emails 
![image](https://user-images.githubusercontent.com/15824252/126523967-d1d63d81-0861-4446-8bec-a9b3739d682b.png)


- tested on approval: 

![image](https://user-images.githubusercontent.com/15824252/126527204-226df228-5c0e-446e-b2e6-4c7eb01346b6.png)


looks great thankyou @blabadi and @anncatton
