### ISSUE TITLE
[UI+Data Hookup] Email to Applicant: Application Approved

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#46]
## Goal
Using the template built in https://github.com/icgc-argo/dac-ui/issues/66 build and hookup the email that is sent to the applicant when their application is approved.

Mockup in zeplin: https://zpl.io/VQJYDmA
![image](https://user-images.githubusercontent.com/18424138/120834872-993e5300-c531-11eb-9c0d-c736279c916e.png)

## Expected Outcomes
- [x] The email has the correct content
- [ ] 1. Link Data Access Agreement TBD (likely to a policy page on icgc-argo.org)
- [ ] 2. Links
`ICGC ARGO Data Platform` goes to  https://platform.icgc-argo.org/
`ICGC 25K Data Portal` goes to https://dcc.icgc.org/
`icgc-argo.org` goes to https://www.icgc-argo.org/
- [ ] 3. Links
`Help Guides for Accessing Controlled Data` goes to https://docs.icgc-argo.org/docs/data-access/data-download
`Contact the ICGC DACO team` goes to  https://platform.icgc-argo.org/contact
- [ ] The View Your Application button takes them to their approved application (log in first if needed), landing on the introduction section 
- [x] The email has the correct application data coming through
- [x] The email is sent to the applicant/PI's google email and institutional email addresses AND if the submitter is not the applicant/PI - send the email to their gmail address too. 
- [x] The email is triggered when DACO Admin confirms the approval - i.e. clicking this `approve for access` button from this modal:
![image](https://user-images.githubusercontent.com/18424138/120835680-a1e35900-c532-11eb-84f6-0307c290ca96.png)

**Comment by rosibaj** [comment]
tested July 21, 2021 
ooks great thank you @blabadi!!

**Comment by kcullion** [comment]
@blabadi @rosibaj just wondering if there was a reason this call to action was not included
![image](https://user-images.githubusercontent.com/18424138/126543084-20f9e095-95be-4d5d-8722-bbff843c51db.png)

**Comment by blabadi** [comment]
no wasn't intentional I'm blind

**Comment by blabadi** [comment]
I probably should apply for disability benefits :p

**Comment by kcullion** [comment]
haha no worries @blabadi I think we can leave it out for now
