### ISSUE TITLE
[UI + Data Hookup] Email to Applicant: Submitted Application received by DACO 

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#48]
## Goal
To first build the email template with all types of content/components required overall. Then customize this template for this one specific email that gets sent to the applicant when they submit their application. 

## Email templating service to use
As discussed with @samrichca
First, build the email template using https://mjml.io/ 
(I played around with this template and got it pretty close to what we need: https://mjml.io/try-it-live/templates/austin)

## General Email Template Specs
The following UI components will be needed for any MVP email template (see screenshot below for numbering)
- [ ] 1. Email logo header (can see an example: https://zpl.io/VQJY1Wx). Link logo and purple underlined copy to https://daco.icgc-argo.org
- [ ] 2. Email title bar (can see an example: https://zpl.io/VQJY1Wx) - the title content will be different for each email
- [ ] 3. Email content salutation and intro copy (can see an example: https://zpl.io/VQJYDmA). 
This will feed in the applicant's full name like Dear `title` `first name` `last name` `suffix`,
- [ ] 4. Application info box. In this example: https://zpl.io/VQJYDmA the first portion of this box is reused throughout other emaills 
![image](https://user-images.githubusercontent.com/18424138/120524495-1be5d780-c3a5-11eb-8b9a-c6756714927f.png)
- [ ] 5. The second portion of this box is for additional information about the application after it's been approved, such as access info.
![image](https://user-images.githubusercontent.com/18424138/120524602-3b7d0000-c3a5-11eb-8743-ee1b098c8caa.png)

- [ ] 6. Email content can continue and include things such as numbered lists, and links. See this example for the most variation: https://zpl.io/VQJYDmA
- [ ] 7. Email callout box. This can sometimes contain blue instructions such as: https://zpl.io/VQJYDmA or just a purple button that will take the user, usually back to the application.  
![image](https://user-images.githubusercontent.com/18424138/120707939-ec100000-c488-11eb-803e-7f906aaccf40.png)

- [ ] 8. Email content closing. This is generally the same closing with different help guide links for each email and signing off as ICGC DACO. 
- [ ] 9. Email footer. This contains important content and links reused from the DACO website. 
Links include:
- Contact Us goes to https://platform.icgc-argo.org/contact
- Policies & Guidelines `link TBD`
- Help Guides `link TBD`
- Controlled Data Users `link TBD`
- ICGC ARGO Website link to https://www.icgc-argo.org/
- ARGO Data Platform link to https://platform.icgc-argo.org/

![image](https://user-images.githubusercontent.com/18424138/120523805-5bf88a80-c3a4-11eb-8bcc-c18a6dbc8b13.png)

## Data hookup for this specific email 
Using the template just built, hide/remove the components that aren't needed for this specific email: zeplin design: https://zpl.io/VQJY1Wx
![image](https://user-images.githubusercontent.com/18424138/120819709-d3075d80-c521-11eb-9227-45782c7a67b2.png)
- [ ] The email has the correct content
- [ ] The email links go to the correct spots 
For now, please just link `contact the ICGC DACO team` to https://platform.icgc-argo.org/contact
(other links are TBD)
- [ ] The email has the correct application data coming through
- [ ] The email is sent to the applicant/PI's google email and institutional email addresses AND if the submitter is not the applicant/PI - send the email to their gmail address too. 
- [ ] The email is triggered when an applicant submits an application (hitting this button in the Sign & Submit section)
![image](https://user-images.githubusercontent.com/18424138/120827136-1f09d080-c529-11eb-8abf-6bf94dcdba2b.png)

**Comment by blabadi** [comment]
Kim quickly reviewed the email and found the following to fix
table padding in application box needs tweaking

![image.png](https://images.zenhubusercontent.com/5c99083bd2fde800015cf9fa/201f3272-1f49-455e-b754-1cd050ac03da)

**Comment by kcullion** [comment]
@blabadi this email looks great to me. 
I forgot to mention one thing, but I made a new ticket as a nice to have at the end (unless it's easier to fix that before doing the rest of the applicant emails)

https://github.com/icgc-argo/dac-api/issues/66

**Comment by rosibaj** [comment]
email verified in mailhog
