### ISSUE TITLE
[BE] Update Search API for sortable columns  

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#49]
- [x] update the search endpoint  https://dac.dev.argo.cancercollaboratory.org/api/api-docs/#/Application/get_applications_  so that the DACO Admin can sort by Ethics Letter Status column `ethicsRequired`
- [x] Some of the sorting is not responding as expected. These fields sorts x:desc, even if i use x:asc
  - googleEmail
  - applicantDisplayName
  - primaryAffiliation

**Comment by rosibaj** [comment]
veridied - soring on all columns appears to be working as expected now.
