### ISSUE TITLE
Fix api version response

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/dac-api#53]
![image.png](https://images.zenhubusercontent.com/5c99083bd2fde800015cf9fa/8bdb3319-66ee-4ad6-b009-dc7beac84f47)

**Comment by kcullion** [comment]
looks good!

**Comment by rosibaj** [comment]
looks good: rending from UI correctly as well: 
![image](https://user-images.githubusercontent.com/15824252/123657938-43db2600-d7ff-11eb-90e5-1ef840b6b81e.png)
