### ISSUE TITLE
🐛 Requested Revisions did not unlock the correct sections

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#58]
## Describe the bug
When I used postman to request revisions, I revised to open the applicant, institutional rep, ethics, and signature sections.
For DACO-51.
But when I look at the application when logged in as the applicant, I only see two sections unlocked for edits

![image](https://user-images.githubusercontent.com/18424138/123699425-448ab100-d82d-11eb-8b8b-577f2fde762a.png)

When going to the get applications endpiont, it shows the Institutional Rep section as locked: 
![image](https://user-images.githubusercontent.com/18424138/123700258-3b4e1400-d82e-11eb-9150-5542d837ae13.png)

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Go to https://dac.qa.argo.cancercollaboratory.org/applications/DACO-51?section=terms
2. Have a look at the sections that are open for revisions. 

## Expected behaviour

- [ ] the sections I reopened for revisions should be correctly unlocked and showing on the UI

![image](https://user-images.githubusercontent.com/18424138/123699696-903d5a80-d82d-11eb-9f62-42e80f867b2f.png)

**Comment by blabadi** [comment]
I think the second point 
```
the sign and the submit section should always have an orange pencil icon but be disabled until the user interacts with all other revision sections. When it's enabled and the user uploads a new file, that orange pencil icon would change to a green pencil until they resubmit. 
```

is a front end bug

**Comment by kcullion** [comment]
yes @blabadi you are correct - sorry this is part of another ticket that hasn't been done yet. I will remove it from this ticket: https://github.com/icgc-argo/dac-ui/issues/96

**Comment by kcullion** [comment]
I tried with a new application and unlocked all possible sections and it worked this time. Thanks @blabadi !

Question, the API allowed me to leave some of the revision details blank for a "true" - but that's ok right as that validation happens on the front end?

**Comment by blabadi** [comment]
it won't harm to add extra validation on the backend too, but since we trust that our reviewers won't hack the api this can be considerd less urgent than say missing validation in the application forms

**Comment by kcullion** [comment]
@blabadi yes good point. I've moved the ticket, no need to add extra validation!
