### ISSUE TITLE
Institutional Rep - make google email not required

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#63]
As discussed over slack, please make the google email field not required so it doesn't mark this section as incomplete (we don't require google address for Inst Rep)

![image](https://user-images.githubusercontent.com/18424138/123841951-3183e980-d8de-11eb-9ee1-5b1ab1d7bab9.png)

**Comment by rosibaj** [comment]
@kcullion is ui correctly displaying not required for this?

**Comment by kcullion** [comment]
@rosibaj we don't need google email for the institutional rep. Talked to @blabadi and he's going to just make it not required

**Comment by rosibaj** [comment]
@kcullion so no ui changes needed at this time to support this change then>

**Comment by kcullion** [comment]
@rosibaj no UI changes needed

**Comment by kcullion** [comment]
tested this @blabadi and now if I put google address in API it doesn't mark that section as incomplete. thanks!
