### ISSUE TITLE
🐛 Project Information: Add lay summary to API

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#64]
## Describe the bug

- [ ] For the Project info section, we need to add the lay summary text area to the API. It's a required field with the same validation as the other text areas on the page. 

![image](https://user-images.githubusercontent.com/18424138/123861155-d5788f80-d8f4-11eb-9080-2e2e8e8d1152.png)

**Comment by kcullion** [comment]
Tested this and it works, I can see it come through on the UI now.

**Comment by rosibaj** [comment]
can confirm that i see this as well.
