### ISSUE TITLE
🐛 Collaborator section stays incomplete after fixing primary affiliation   

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#65]
## Describe the bug
I think this is a bug, but correct me if I"m wrong. 
When I make the primary affiliations match, then not match, then match again - the collaborators still reports as incomplete. 

see https://dac.qa.argo.cancercollaboratory.org/applications/DACO-53?section=applicant as the reference

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Make it so all of your primary affiliations match for section A, B and C (OICR). So these sections are marked as complete
2. Change the Primary affiliation of the applicant (eg. Google)
3. As expected, section B and C show errors
4. Now change the Primary affiliation of section A back to the matching value for B and C (OICR)
5. Section B shows as complete, but Section C still shows the incomplete status
![image](https://user-images.githubusercontent.com/18424138/123849704-1e294c00-d8e7-11eb-8fc3-5c7c1b032a10.png)
![image](https://user-images.githubusercontent.com/18424138/123849811-3d27de00-d8e7-11eb-9ed2-7701be433c0f.png)

## Expected behaviour
If I fix section A to make the primary affiliations match again, section C should not report an error

**Comment by rosibaj** [comment]
tested from ui - this looks to be working correctly now.  thank you @blabadi
