### ISSUE TITLE
🐛 Revising section A marks section B as REVISIONS MADE too

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#67]
## Describe the bug
For https://dac.qa.argo.cancercollaboratory.org/applications/DACO-55?section=applicant

I had section A and B open for revisions. When I made an update in section A and clicked "send" in postman, it marked sections A and B as REVISIONS MADE (with green check)

![image](https://user-images.githubusercontent.com/18424138/123857124-f25e9400-d8ef-11eb-9ca8-22e48f5439d4.png)

## Expected behaviour
Only section A should have been marked as revisions made

**Comment by kcullion** [comment]
@blabadi I checked this out and this could be related to bugs we found between section A and B for Justin https://github.com/icgc-argo/dac-ui/issues/188

So not sure you need to action on this:
1. when I make a change in section A, it gets checked off and section B remains "Revisions Requested"
2. When I make a change in section B (from the UI form) the API doesn't record that as "Revisions Made" - the orange pencil stays showing in section B
![image](https://user-images.githubusercontent.com/18424138/124987451-e3bc5f00-e00a-11eb-9c65-263f324d8d8e.png)

![image](https://user-images.githubusercontent.com/18424138/124987289-afe13980-e00a-11eb-8cf5-86c93e430b2b.png)

**Comment by rosibaj** [comment]
Tested Jul 08 2021; seeing the same issues as Kim
![image](https://user-images.githubusercontent.com/15824252/124992100-8cb98880-e010-11eb-8ee9-5ede1319ecf4.png)


@blabadi I will move this back to in progress until this is resolved.

**Comment by rosibaj** [comment]
tsted this from the UI - was able to change just section A and only section  A updated!
