### ISSUE TITLE
🐛 After approval, Collaborators and sometimes Ethics needs to be marked as CAN_EDIT

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#68]
## Describe the bug

- [ ] When I approve an application, **that has an ethics letter**, collaborators and ethics sections are marked as COMPLETE but they should be CAN_EDIT 

![image](https://user-images.githubusercontent.com/18424138/123969176-f63cf580-d985-11eb-83ab-a4f80d2ccf5c.png)

- [ ] When I declare "false" for the ethics letter, after approval, this section should be LOCKED - right now it is marked as COMPLETE.
![image](https://user-images.githubusercontent.com/18424138/123995861-bcc3b480-d99c-11eb-9abd-7343a6aaa950.png)

## Expected behaviour
The purple pencil should be showing in the sidebar, but we don't yet have a state for the api to report the CAN_EDIT sections on APPROVED state applications.

**Comment by rosibaj** [comment]
lgtm thank you @blabadi !
