### ISSUE TITLE
🐛 Should not be able to submit duplicate urls for publications

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-api#83]
## Describe the bug
Noticed the API doesn't validate whether there's duplicate URLs (at least it seemed this way when I used the same valid url in the 4th and 5th fields.) May be worth double checking whether that logic is present or needs improvement.

## Expected behaviour
should not be allowed to submit duplicate urls for publications,

**Comment by kcullion** [comment]
@blabadi  tested this in the UI and it just erases the url that I try to add twice. I see we are to implement an error message post release. And I see this in postman...I guess that means this is working:) 
![image](https://user-images.githubusercontent.com/18424138/126544600-8a03125f-da5d-4bf8-80cf-94a0c8d66781.png)

**Comment by rosibaj** [comment]
@kcullion yea, the ticket justin is currently working on shoudl adress the ui issue!

**Comment by kcullion** [comment]
@rosibaj yeah I just assumed it was this one for post release https://github.com/icgc-argo/dac-ui/issues/138

**Comment by rosibaj** [comment]
Aug 16, deployed to production (ui 0.23.1 / api 0.32.0)
