### ISSUE TITLE
🐛 LOW PRIORITY: Admin table sort is case sensitive

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#84]
## Describe the bug
This is very low priority.
When sorting the google email addresses, the capitalized emails are at the top and not within alpha order.

![image](https://user-images.githubusercontent.com/18424138/125097095-c2f41800-e0a3-11eb-89ca-383b6cce8f7e.png)

## Expected behaviour
The sort should be alpha order for this column, no matter the casing

**Comment by rosibaj** [comment]
@blabadi should this be in QA column?

**Comment by blabadi** [comment]
Yes moved

**Comment by rosibaj** [comment]
tested on QA lgtm! thank you very much @blabadi !
