### ISSUE TITLE
Daco2Ego connection - Make controlled users list 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/dac-api#93]
- https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Integrations+-+Daco2Ego 

Generate a DACO File
- [ ] Create an endpoint to generate a `controlled user list` file from the DACO database (
  - GET /export/approved-users/?format=daco-file-format`
  - accept format as a query parameter.  we may have future export types. 
  - Access of this endpoint needs to be secured to only DACO admins or an application with that permission (DACOREVIEW.WRITE)
  - File should contain the headers in DACOFileFormat

**Comment by rosibaj** [comment]
@anncatton i dont see this endpoint in swagger - am i missing something?

**Comment by anncatton** [comment]
@rosibaj the endpoint should return a 400 error if you make the request without the `format=daco-file-format` query param (we can update the endpoint to deal with other file formats if/when needed), but you'll have to test that scenario in postman, not swagger

**Comment by rosibaj** [comment]
@anncatton i have tested the file and there are a couple things:
- we need the column `CSA`  with a value of TRUE for all users. this is to be compatible with ICGC 25K Daco2Ego. 
- regading the id column; i think its ok that it is not there, especially as there is no mapped DACO field, but will that column being missing interfere at all with the daco2ego scripts?


Wiki for file format: https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Integrations+-+Daco2Ego#IntegrationsDaco2Ego-DACOFileFormat

**Comment by anncatton** [comment]
daco2ego finds users in ego by their email + provider type (GOOGLE for ARGO), so it should be fine without this id field
